INSERT INTO users (id,email,password,first_name,last_name,birthday,country,city) VALUES (1,"tempor.diam.dictum@nuncest.net","secret","Victoria","Crawford","1986-07-22","Lesotho","Waalwijk"),(2,"rhoncus@ipsum.ca","secret","Sybil","Burke","1999-07-06","Portugal","Ancaster Town"),(3,"massa.non.ante@in.net","secret","Ava","Watson","1995-09-10","Senegal","Essex"),(4,"varius@elit.org","secret","Ori","Heath","1986-05-29","Singapore","Belgaum"),(5,"risus@aclibero.co.uk","secret","Ross","Mccray","1990-02-23","Singapore","Oyace"),(6,"nibh.enim.gravida@blandit.org","secret","Penelope","Harris","1989-03-15","United States","High Wycombe"),(7,"magna@fringillami.co.uk","secret","Gail","Leach","1993-03-07","Indonesia","New Glasgow"),(8,"eleifend@blandit.ca","secret","Meghan","Ballard","1993-08-09","Myanmar","Ried im Innkreis"),(9,"Duis.cursus.diam@adipiscingelit.edu","secret","Orli","Lawson","1995-07-18","Chile","Saint-Laurent"),(10,"nisi.Aenean.eget@dictum.edu","secret","Kylie","Duke","1995-10-10","United States Minor Outlying Islands","Sandy");
INSERT INTO users (id,email,password,first_name,last_name,birthday,country,city) VALUES (11,"ligula@purusNullamscelerisque.com","secret","Allegra","Tyler","1995-09-12","Denmark","Baltimore"),(12,"facilisis.vitae.orci@miac.com","secret","Meredith","Pate","1997-04-30","Liechtenstein","Feltre"),(13,"semper.rutrum.Fusce@velfaucibusid.co.uk","secret","Wade","Mccoy","1991-09-15","Korea, North","Alva"),(14,"dignissim.lacus@Praesentinterdum.co.uk","secret","Clio","Tucker","1997-05-23","Saint Kitts and Nevis","Meißen"),(15,"quam@enimEtiamimperdiet.co.uk","secret","Olga","Frost","1999-06-06","Angola","Fort St. John"),(16,"Donec@nasceturridiculus.edu","secret","Nigel","Castaneda","1992-11-15","India","Birmingham"),(17,"vel@semper.com","secret","Mechelle","Mcmillan","1987-12-28","Barbados","Capena"),(18,"risus@Sedneque.net","secret","Tiger","Clemons","1987-01-16","Jersey","Tiruvottiyur"),(19,"tempor.est@feugiat.edu","secret","Scarlett","Massey","1996-08-23","India","Götzis"),(20,"tempor@pede.org","secret","Avye","Nash","1989-09-07","Dominica","Yumbel");
INSERT INTO users (id,email,password,first_name,last_name,birthday,country,city) VALUES (21,"consectetuer@lacusQuisquepurus.com","secret","Tana","Reilly","1998-04-16","Gambia","Moerbeke"),(22,"nisl.Nulla@lacusvariuset.co.uk","secret","Sharon","Chapman","1995-02-05","Greenland","Castelvecchio Calvisio"),(23,"lorem.sit.amet@mattis.com","secret","Raphael","Bennett","1993-06-22","Martinique","Panihati"),(24,"velit.Cras@acmattisvelit.com","secret","Kellie","King","1986-12-20","Côte D'Ivoire (Ivory Coast)","Inuvik"),(25,"elementum@massa.edu","secret","Quinn","Wyatt","1989-06-26","Myanmar","Tsiigehtchic"),(26,"semper@Etiam.edu","secret","Ora","Phillips","1985-01-28","Montserrat","Ruddervoorde"),(27,"Cras@IntegerurnaVivamus.edu","secret","Lucius","Browning","1999-09-29","Albania","Alto del Carmen"),(28,"est.Nunc.laoreet@enimnectempus.net","secret","Perry","Conley","1990-02-11","Venezuela","Corswarem"),(29,"vel.lectus@ut.edu","secret","Cameron","Ward","1987-04-04","Brazil","Veraval"),(30,"non.massa@pedeSuspendissedui.net","secret","Rose","Levine","1987-12-18","Liberia","Cincinnati");
INSERT INTO users (id,email,password,first_name,last_name,birthday,country,city) VALUES (31,"magna.Cras.convallis@ut.ca","secret","Montana","Lindsay","1988-03-19","Saudi Arabia","Braives"),(32,"ac.turpis@estconguea.co.uk","secret","Zephania","Holt","1993-05-16","Equatorial Guinea","Coutisse"),(33,"arcu.ac@blanditcongueIn.ca","secret","Diana","Baird","1986-03-04","Marshall Islands","Fossato Serralta"),(34,"adipiscing@turpisegestas.org","secret","Ora","Johns","1987-05-28","Senegal","GrivegnŽe"),(35,"arcu.Morbi.sit@elementum.edu","secret","Marcia","Horn","1992-04-22","Tokelau","Carpignano Salentino"),(36,"lorem.fringilla@convallisest.ca","secret","Buckminster","Kaufman","1990-08-31","Palestine, State of","Dion-Valmont"),(37,"parturient.montes.nascetur@lectus.com","secret","Ingrid","Alston","1990-10-27","Faroe Islands","Göteborg"),(38,"luctus.aliquet.odio@Sedauctor.co.uk","secret","Eagan","Pennington","1990-11-23","Japan","Reyhanlı"),(39,"tellus@feugiatmetussit.net","secret","Chaim","Shaw","1991-01-27","Haiti","Matagami"),(40,"felis.Donec@natoquepenatibus.net","secret","Melodie","Cline","1988-03-26","Indonesia","Las Condes");
INSERT INTO users (id,email,password,first_name,last_name,birthday,country,city) VALUES (41,"id@nonlobortis.com","secret","Phoebe","Kramer","1998-02-14","South Georgia and The South Sandwich Islands","Hachy"),(42,"erat.Vivamus.nisi@vitaeeratVivamus.co.uk","secret","Ava","Frederick","1985-05-16","Samoa","Caccamo"),(43,"orci.Donec@nonnisiAenean.org","secret","Martina","Glover","1988-11-27","Andorra","Crehen"),(44,"id.ante.dictum@rhoncus.co.uk","secret","Quincy","Hardy","1988-03-11","Brunei","Qualicum Beach"),(45,"massa.Suspendisse@montes.com","secret","Sebastian","Mason","1996-12-29","Turkey","La Magdeleine"),(46,"turpis.egestas@duiFusce.org","secret","Jane","Leblanc","1990-02-01","Bonaire, Sint Eustatius and Saba","Matamata"),(47,"Donec@egetipsum.com","secret","Jamalia","Hogan","1998-06-29","Nauru","Glendon"),(48,"penatibus@vestibulumloremsit.net","secret","Upton","Daugherty","1988-11-12","France","Williams Lake"),(49,"Suspendisse@convallis.com","secret","Graiden","Richmond","1988-11-09","Viet Nam","Stirling"),(50,"amet.consectetuer@Phasellus.edu","secret","Thaddeus","Lowe","1993-06-18","Timor-Leste","Meeffe");
INSERT INTO users (id,email,password,first_name,last_name,birthday,country,city) VALUES (51,"consequat.lectus@elitCurabitursed.net","secret","Cleo","Serrano","1992-08-13","Mongolia","Ferness"),(52,"aliquet@erat.co.uk","secret","Patricia","Head","1991-01-31","Wallis and Futuna","Jamoigne"),(53,"posuere.vulputate.lacus@nislelementumpurus.ca","secret","Quynn","Brennan","1989-10-21","Tonga","Enna"),(54,"Nulla.facilisi.Sed@aptenttacitisociosqu.com","secret","Quemby","Mitchell","1998-03-04","Bulgaria","Driekapellen"),(55,"varius.et@necorciDonec.co.uk","secret","Alfreda","Emerson","1996-07-18","Syria","Nizip"),(56,"Phasellus@vitaesodalesat.ca","secret","Isabelle","Vega","1998-07-30","Kuwait","Autelbas"),(57,"dui.nec.urna@mollisvitae.org","secret","Rhiannon","Peters","1996-09-05","Yemen","Hospet"),(58,"eget.metus.eu@gravidamolestie.edu","secret","Ocean","Gates","1992-07-13","Bosnia and Herzegovina","Portofino"),(59,"Nunc.sollicitudin@enimmi.ca","secret","Hoyt","Erickson","1985-01-03","Indonesia","Timon"),(60,"euismod@Maurisvestibulumneque.ca","secret","Teagan","Deleon","1985-09-08","Venezuela","West Vancouver");
INSERT INTO users (id,email,password,first_name,last_name,birthday,country,city) VALUES (61,"blandit@augueut.edu","secret","Winter","Guerrero","1993-06-22","Angola","Urbe"),(62,"in.aliquet@facilisisvitaeorci.com","secret","Rebekah","Mcneil","1990-03-28","United States","Orangeville"),(63,"primis@estconguea.edu","secret","Kiayada","Rocha","1997-03-23","Burundi","Camarones"),(64,"ut.odio@nisimagna.com","secret","Hammett","Willis","1986-12-08","China","Chañaral"),(65,"Aenean.eget.metus@musDonec.com","secret","Dane","Phelps","1997-03-12","United Arab Emirates","Visso"),(66,"nec@semper.com","secret","Jaden","Rodgers","1997-07-24","South Africa","Cuenca"),(67,"dapibus@Cras.edu","secret","Bernard","Workman","1999-04-15","Jersey","Chaitén"),(68,"consectetuer@Etiamgravidamolestie.edu","secret","Xyla","Crawford","1999-09-02","Spain","Taber"),(69,"ut@suscipitest.com","secret","Paki","Payne","1999-09-15","Bonaire, Sint Eustatius and Saba","San Pancrazio Salentino"),(70,"dictum.eleifend.nunc@sitametrisus.com","secret","Cherokee","Sears","1992-04-07","United Kingdom (Great Britain)","Grumo Appula");
INSERT INTO users (id,email,password,first_name,last_name,birthday,country,city) VALUES (71,"facilisis.Suspendisse@gravidanon.ca","secret","Alfonso","Sykes","1999-11-05","Brazil","Fort Providence"),(72,"Sed.dictum@est.edu","secret","Jacob","Molina","1991-11-02","Serbia","Memphis"),(73,"Morbi.accumsan@ipsumDonec.org","secret","Patricia","Williams","1991-04-03","Greece","Vallepietra"),(74,"luctus.aliquet.odio@arcuAliquamultrices.net","secret","Yardley","Mcknight","1990-10-21","Montserrat","Rosarno"),(75,"malesuada@nondapibusrutrum.com","secret","Mariam","Whitley","1996-08-11","Oman","Pugwash"),(76,"lacus.varius.et@Fuscemilorem.com","secret","Kylee","Manning","1994-08-16","Ecuador","Oxford"),(77,"fermentum@aarcuSed.com","secret","Nathan","Madden","1991-09-13","Mexico","New Orleans"),(78,"lacinia.vitae@felis.ca","secret","Brynne","Kane","1985-02-07","San Marino","Paris"),(79,"ipsum.Phasellus.vitae@anteVivamusnon.com","secret","Montana","Clayton","1994-12-01","Svalbard and Jan Mayen Islands","Kansas City"),(80,"nisl.Quisque.fringilla@vel.org","secret","Heidi","Ruiz","1988-10-05","Singapore","Vinci");
INSERT INTO users (id,email,password,first_name,last_name,birthday,country,city) VALUES (81,"semper.tellus.id@Uttinciduntorci.edu","secret","Holly","Guthrie","1987-08-27","Tonga","Habay-la-Neuve"),(82,"ut@consequat.net","secret","Samson","Horton","1992-05-30","Cape Verde","Cabras"),(83,"vulputate@idantedictum.edu","secret","Keely","Crane","1987-05-22","Azerbaijan","Gonnosnò"),(84,"auctor.vitae@neccursus.ca","secret","Hayes","Martin","1992-11-05","Belgium","Morhet"),(85,"vulputate.posuere@tincidunt.co.uk","secret","Yardley","Leonard","1989-02-17","Samoa","Colbún"),(86,"quam.Pellentesque@facilisis.com","secret","Kameko","Marks","1999-04-10","Cocos (Keeling) Islands","Gualdo Tadino"),(87,"Donec@Proinsedturpis.net","secret","Chava","Stephens","1998-07-03","French Polynesia","Stevenage"),(88,"mus@at.co.uk","secret","Lucius","Bolton","1999-10-09","Estonia","Rock Springs"),(89,"ipsum.nunc.id@estNunclaoreet.net","secret","Yvette","Crosby","1999-12-01","Croatia","Lévis"),(90,"facilisis.non.bibendum@senectus.net","secret","Garth","Black","1998-02-28","Latvia","Zapallar");
INSERT INTO users (id,email,password,first_name,last_name,birthday,country,city) VALUES (91,"tempus@ut.org","secret","Fuller","Kelley","1994-09-19","Libya","Cranbrook"),(92,"purus@idante.ca","secret","Wayne","Gordon","1999-11-12","Nauru","Esterzili"),(93,"vitae.aliquet.nec@arcuiaculis.com","secret","Murphy","Gates","1996-12-03","Israel","Birmingham"),(94,"Aenean.massa@inmagnaPhasellus.com","secret","Dylan","Higgins","1988-06-14","Equatorial Guinea","Gubbio"),(95,"Mauris@nulla.net","secret","Reece","Pittman","1988-02-06","Korea, North","Lanester"),(96,"semper.et@estac.com","secret","Kamal","Delgado","1987-09-04","Finland","Lavoir"),(97,"orci@Curabiturmassa.ca","secret","Lionel","Strickland","1986-03-11","Kenya","Vaux-sous-ChŽvremont"),(98,"ac@facilisisSuspendisse.edu","secret","Shelby","Cortez","1992-01-06","Ghana","Kelowna"),(99,"vel@semperauctorMauris.edu","secret","Lillian","Gay","1997-09-25","Holy See (Vatican City State)","Tiel"),(100,"faucibus@utlacus.ca","secret","Yen","Rowe","1992-03-19","Tonga","Plancenoit");
/
SELECT * FROM human_migrations;
DESCRIBE human_migrations;

DELETE FROM human_migrations WHERE id>200;

ALTER TABLE human_migrations MODIFY arrival_city varchar(191);
ALTER TABLE human_migrations MODIFY arrival_country varchar(191);
/
INSERT INTO `human_migrations` (`departure_country`,`departure_city`,`adults`,`children`,`reason`,`user_id`) VALUES ("Austria","Steyr",1,9,"Other",59),("Sweden","Hudiksvall",5,5,"Education",69),("Poland","Zielona Góra",3,2,"Other",29),("Australia","Greater Hobart",4,1,"Personal",80),("Austria","St. Johann in Tirol",5,2,"Economics",31),("Turkey","Istanbul",2,7,"Education",5),("Nigeria","Sokoto",5,6,"Education",27),("Sweden","Hofors",3,8,"Education",13),("Italy","Crotta d'Adda",2,7,"Other",65),("Ireland","Cork",5,9,"Other",76);
INSERT INTO `human_migrations` (`departure_country`,`departure_city`,`adults`,`children`,`reason`,`user_id`) VALUES ("Poland","Tarnów",5,5,"War",46),("France","Nîmes",3,10,"Economics",95),("India","Haridwar",4,5,"Religion",31),("United Kingdom","Livingston",3,7,"Other",63),("Canada","Watson Lake",5,2,"Education",90),("Costa Rica","Quesada",5,10,"Religion",26),("Netherlands","Gorinchem",4,4,"Religion",86),("New Zealand","Feilding",5,3,"Other",31),("Spain","Getafe",5,9,"Other",84),("Turkey","Edremit",3,9,"Religion",78);
INSERT INTO `human_migrations` (`departure_country`,`departure_city`,`adults`,`children`,`reason`,`user_id`) VALUES ("Australia","Parramatta",4,2,"Other",41),("Austria","Villach",2,8,"Other",33),("Brazil","Nova Iguaçu",4,10,"Other",95),("Spain","Lugo",3,3,"Religion",12),("Sweden","Upplands Väsby",3,1,"Economics",70),("France","Lunel",5,3,"Religion",76),("Nigeria","Bauchi",1,9,"Education",44),("Germany","Mülheim",2,2,"War",3),("Austria","Rankweil",1,6,"War",62),("United States","West Jordan",4,10,"Education",46);
INSERT INTO `human_migrations` (`departure_country`,`departure_city`,`adults`,`children`,`reason`,`user_id`) VALUES ("Netherlands","Geertruidenberg",2,2,"Education",87),("Turkey","İnegöl",2,8,"Other",86),("Costa Rica","San Francisco",3,8,"Education",30),("Ireland","Galway",1,10,"Personal",28),("Canada","Hay River",3,8,"Religion",9),("Canada","Lac-Serent",2,6,"Personal",63),("Costa Rica","Heredia",1,6,"Other",11),("Netherlands","Hindeloopen",2,5,"Economics",58),("Canada","Miramichi",1,7,"Personal",90),("United States","Ketchikan",1,2,"Personal",45);
INSERT INTO `human_migrations` (`departure_country`,`departure_city`,`adults`,`children`,`reason`,`user_id`) VALUES ("Brazil","Pelotas",2,10,"Education",78),("Poland","Pabianice",2,7,"Other",31),("Costa Rica","San José",5,2,"Personal",34),("Italy","Anzi",1,3,"Personal",61),("Australia","Launceston",3,7,"War",64),("Nigeria","Lagos",2,6,"Economics",90),("Germany","Remscheid",2,3,"Education",88),("United Kingdom","Fochabers",5,2,"Religion",59),("India","Silvassa",4,6,"Education",13),("Costa Rica","Carmen",4,4,"Religion",82);
INSERT INTO `human_migrations` (`departure_country`,`departure_city`,`adults`,`children`,`reason`,`user_id`) VALUES ("Italy","Pollein",2,4,"Education",15),("Sweden","Tranås",2,9,"Other",21),("Brazil","Marabá",2,1,"Religion",58),("France","Rouen",5,4,"Other",9),("Canada","Burin",5,2,"Economics",97),("Ireland","Galway",3,2,"Personal",73),("United Kingdom","Rattray",2,4,"Education",22),("Italy","Paternopoli",1,3,"Education",65),("Spain","Logroño",5,6,"Religion",60),("Belgium","Sint-Jans-Molenbeek",5,1,"Religion",21);
INSERT INTO `human_migrations` (`departure_country`,`departure_city`,`adults`,`children`,`reason`,`user_id`) VALUES ("Italy","Portici",4,1,"Religion",92),("United Kingdom","Tullibody",1,4,"Religion",79),("India","Imphal",3,9,"Education",84),("France","Beauvais",4,6,"War",100),("Costa Rica","Barranca",2,4,"Personal",32),("Chile","Navidad",1,9,"Other",66),("Italy","Fauglia",4,2,"Economics",28),("Brazil","Blumenau",1,1,"War",81),("Chile","San Clemente",2,2,"Education",39),("Germany","Hamburg",1,4,"War",56);
INSERT INTO `human_migrations` (`departure_country`,`departure_city`,`adults`,`children`,`reason`,`user_id`) VALUES ("Spain","Mataró",1,1,"War",100),("Canada","Whitchurch-Stouffville",2,2,"War",65),("Turkey","Reyhanlı",4,4,"Education",30),("Costa Rica","San José de Alajuela",1,7,"Religion",52),("Spain","Fuenlabrada",1,6,"Economics",70),("France","Colomiers",3,10,"War",39),("Brazil","Vitória da Conquista",1,4,"Personal",26),("Spain","Gasteiz",3,3,"Other",83),("Poland","Koszalin",1,9,"Education",27),("United Kingdom","Holyhead",2,3,"War",98);
INSERT INTO `human_migrations` (`departure_country`,`departure_city`,`adults`,`children`,`reason`,`user_id`) VALUES ("Costa Rica","Alajuelita",2,9,"Education",71),("Australia","Swan Hill",4,5,"War",81),("Netherlands","Almere",1,10,"Other",76),("Sweden","Finspång",5,3,"War",60),("Poland","Tarnów",2,6,"Education",88),("Italy","Esterzili",2,8,"Religion",5),("United Kingdom","Harlow",5,6,"Education",16),("New Zealand","Christchurch",3,8,"Religion",87),("Belgium","Onoz",2,5,"War",55),("United States","Gresham",2,9,"Other",81);
INSERT INTO `human_migrations` (`departure_country`,`departure_city`,`adults`,`children`,`reason`,`user_id`) VALUES ("Italy","Felitto",2,7,"Personal",37),("Netherlands","Leeuwarden",2,1,"Education",50),("United Kingdom","Birmingham",1,8,"War",74),("Costa Rica","Limón (Puerto Limón)",5,9,"Education",38),("United Kingdom","Mold",5,4,"Religion",69),("Spain","Elx",4,4,"Personal",95),("Costa Rica","Puntarenas",1,9,"Religion",10),("Australia","Palmerston",4,5,"Economics",7),("United Kingdom","Clovenfords",3,6,"Other",71),("France","Tourcoing",1,2,"Religion",62);
INSERT INTO `human_migrations` (`departure_country`,`departure_city`,`adults`,`children`,`reason`,`user_id`) VALUES ("France","Vannes",5,3,"Education",28),("Nigeria","Sokoto",5,1,"Religion",52),("Nigeria","Okigwe",4,6,"Economics",4),("Sweden","Bollnäs",3,10,"Other",89),("Sweden","Lidingo",3,2,"Other",4),("Nigeria","Sokoto",4,8,"Education",97),("France","Montauban",1,4,"War",69),("Austria","Vienna",3,8,"Personal",30),("New Zealand","Morrinsville",2,3,"Personal",10),("Brazil","Cametá",1,7,"Economics",98);
INSERT INTO `human_migrations` (`departure_country`,`departure_city`,`adults`,`children`,`reason`,`user_id`) VALUES ("Turkey","Silvan",2,8,"Education",37),("Spain","Oviedo",1,5,"Other",60),("Germany","Zwickau",4,7,"Education",24),("Turkey","Izmir",1,4,"Religion",80),("India","Kanchipuram",4,2,"Economics",39),("New Zealand","Masterton",5,7,"Personal",90),("Nigeria","Uyo",1,2,"Economics",1),("Italy","Sant'Angelo a Fasanella",5,3,"Religion",46),("Netherlands","Zoetermeer",4,5,"War",90),("Sweden","Norrköping",1,4,"Economics",1);
INSERT INTO `human_migrations` (`departure_country`,`departure_city`,`adults`,`children`,`reason`,`user_id`) VALUES ("Australia","Launceston",5,1,"Education",40),("Costa Rica","San Pablo",2,6,"Personal",55),("Canada","Edmundston",3,6,"War",61),("Brazil","Mogi das Cruzes",3,10,"Other",86),("New Zealand","Rangiora",2,9,"Economics",83),("United States","Nashville",5,4,"War",57),("Nigeria","Bida",1,5,"Personal",7),("Italy","Massello",2,2,"Personal",80),("France","Douai",3,10,"Religion",6),("Germany","Schifferstadt",2,5,"Religion",51);
INSERT INTO `human_migrations` (`departure_country`,`departure_city`,`adults`,`children`,`reason`,`user_id`) VALUES ("Ireland","Belfast",5,5,"War",35),("Netherlands","Lelystad",4,2,"War",96),("Canada","Beausejour",4,7,"Education",90),("Poland","Ostrowiec Świętokrzyski",4,3,"War",85),("Austria","Rechnitz",3,3,"Economics",63),("Sweden","Värnamo",2,2,"Education",76),("Australia","Whyalla",3,4,"War",5),("Turkey","Çermik",2,10,"War",32),("Netherlands","Hengelo",2,5,"Religion",19),("Turkey","Polatlı",2,7,"Other",73);
INSERT INTO `human_migrations` (`departure_country`,`departure_city`,`adults`,`children`,`reason`,`user_id`) VALUES ("Costa Rica","Patarrá",4,5,"Religion",19),("Ireland","Cork",3,5,"Religion",5),("Netherlands","Lelystad",3,6,"Education",70),("Canada","Kapuskasing",4,1,"Religion",83),("Nigeria","Gboko",3,8,"Personal",61),("Poland","Radom",5,5,"Education",99),("United Kingdom","Renfrew",3,3,"Economics",39),("Canada","Stratford",5,6,"War",47),("Belgium","Nadrin",2,9,"War",6),("Brazil","Canoas",3,9,"Religion",66);
INSERT INTO `human_migrations` (`departure_country`,`departure_city`,`adults`,`children`,`reason`,`user_id`) VALUES ("Nigeria","Buguma",3,2,"Other",37),("Brazil","Valparaíso de Goiás",2,3,"Other",80),("Turkey","Karacabey",3,5,"Religion",82),("Netherlands","Doetinchem",4,10,"Education",40),("Spain","Melilla",3,1,"Other",78),("Australia","Melton",1,9,"Religion",4),("New Zealand","Feilding",4,2,"Personal",83),("New Zealand","Queenstown",2,9,"Education",56),("Turkey","Kahramanmaraş",3,9,"Personal",32),("Netherlands","Hoogeveen",1,9,"Religion",46);
INSERT INTO `human_migrations` (`departure_country`,`departure_city`,`adults`,`children`,`reason`,`user_id`) VALUES ("Turkey","Pınarbaşı",2,10,"War",43),("Poland","Rzeszów",1,1,"Other",33),("United States","Henderson",3,2,"Other",80),("Poland","Olsztyn",5,1,"Personal",50),("Italy","Lodine",1,2,"Other",47),("Turkey","Dörtyol",1,10,"Economics",28),("United States","San Antonio",3,3,"Religion",100),("Spain","Santander",2,6,"Education",55),("United Kingdom","Sherborne",1,6,"Economics",62),("United States","Springfield",1,8,"War",77);
INSERT INTO `human_migrations` (`departure_country`,`departure_city`,`adults`,`children`,`reason`,`user_id`) VALUES ("Netherlands","Bolsward",5,6,"Religion",58),("India","Kavaratti",1,8,"Personal",49),("Spain","Melilla",4,7,"Other",59),("New Zealand","Whakatane",2,2,"Other",46),("Canada","Yellowhead County",4,4,"Personal",8),("New Zealand","Dunedin",3,3,"War",97),("Costa Rica","Barranca",2,8,"Religion",9),("Italy","Colli a Volturno",4,9,"Other",10),("Austria","Lauterach",5,9,"Education",2),("Brazil","Aparecida de Goiânia",3,4,"Education",56);
INSERT INTO `human_migrations` (`departure_country`,`departure_city`,`adults`,`children`,`reason`,`user_id`) VALUES ("Sweden","Stockholm",3,2,"Religion",59),("Netherlands","Terneuzen",3,8,"Personal",77),("Australia","Darwin",4,1,"Other",50),("Sweden","Nässjö",1,4,"Religion",4),("Nigeria","Funtua",2,3,"Religion",21),("Italy","Garaguso",2,5,"War",53),("United Kingdom","Salisbury",4,8,"Personal",48),("United Kingdom","Leominster",5,5,"Personal",65),("Turkey","Bostaniçi",4,9,"Economics",74),("Poland","Poznań",3,7,"Religion",12);
INSERT INTO `human_migrations` (`departure_country`,`departure_city`,`adults`,`children`,`reason`,`user_id`) VALUES ("France","Tourcoing",2,8,"Economics",95),("Turkey","İslahiye",4,6,"Economics",11),("Poland","Chełm",1,6,"War",11),("United States","Salt Lake City",5,8,"Religion",37),("Chile","General Lagos",3,6,"Economics",55),("India","Aizwal",4,8,"Other",43),("Australia","Greater Hobart",5,7,"Personal",50),("Netherlands","Eindhoven",4,4,"Economics",23),("New Zealand","Kawerau",4,3,"Religion",42),("Turkey","Bergama",1,10,"War",3);
INSERT INTO `human_migrations` (`departure_country`,`departure_city`,`adults`,`children`,`reason`,`user_id`) VALUES ("Australia","Greater Hobart",2,6,"Education",2),("Chile","Panguipulli",4,3,"Education",2),("Ireland","Cork",5,4,"Religion",1),("Ireland","Cork",3,8,"Economics",8),("Turkey","Manavgat",2,6,"Religion",7),("Australia","Orange",2,8,"Other",1),("Chile","Arica",2,3,"War",3),("United Kingdom","High Wycombe",3,7,"Personal",1),("Australia","Mandurah",3,2,"War",6),("Australia","Darwin",4,5,"Economics",10);
INSERT INTO `human_migrations` (`departure_country`,`departure_city`,`adults`,`children`,`reason`,`user_id`) VALUES ("Turkey","Samsun",5,3,"War",4),("Austria","Höchst",4,6,"Economics",3),("Ireland","Dublin",1,2,"War",2),("Germany","Neubrandenburg",5,6,"War",1),("Turkey","Aydın",4,8,"Education",7),("Belgium","Lamorteau",3,5,"Personal",5),("Turkey","Gönen",4,9,"Personal",5),("Ireland","Dublin",5,2,"Education",6),("Italy","Casalvieri",1,4,"Personal",9),("New Zealand","Kerikeri",3,3,"Personal",8);
INSERT INTO `human_migrations` (`departure_country`,`departure_city`,`adults`,`children`,`reason`,`user_id`) VALUES ("Chile","Illapel",1,6,"War",10),("Italy","Livorno",2,4,"Other",2),("Austria","Sankt Johann im Pongau",3,6,"Other",10),("Sweden","Linköping",1,3,"Religion",10),("United States","Bridgeport",4,6,"Religion",10),("India","Brahmapur",3,9,"Personal",6),("Italy","Lusevera",2,3,"Education",10),("Ireland","Galway",3,8,"Education",5),("India","Thanjavur",4,5,"Religion",1),("Nigeria","Lagos",1,8,"Education",9);
INSERT INTO `human_migrations` (`departure_country`,`departure_city`,`adults`,`children`,`reason`,`user_id`) VALUES ("Sweden","Lerum",5,7,"Economics",1),("Nigeria","Lagos",5,2,"Religion",2),("Canada","Gjoa Haven",3,5,"Economics",6),("Brazil","Itajaí",1,1,"Religion",7),("Belgium","Lustin",1,6,"Economics",7),("Chile","Perquenco",5,6,"War",3),("Brazil","Guarulhos",5,9,"War",8),("United Kingdom","Luton",3,2,"War",3),("United States","Salt Lake City",4,8,"Personal",10),("Poland","Gdańsk",5,6,"Personal",2);
INSERT INTO `human_migrations` (`departure_country`,`departure_city`,`adults`,`children`,`reason`,`user_id`) VALUES ("Costa Rica","Siquirres",4,7,"War",8),("United Kingdom","Denbigh",3,7,"Other",3),("Belgium","Anderlecht",5,7,"Education",1),("Germany","Mörfelden-Walldorf",4,1,"War",8),("Brazil","Bragança",4,6,"Other",3),("Canada","Weyburn",4,3,"Economics",2),("Brazil","Juazeiro",5,8,"Personal",9),("Italy","Montese",3,2,"Religion",10),("Sweden","Vetlanda",2,1,"Education",10),("Turkey","Didim",2,6,"Personal",6);
INSERT INTO `human_migrations` (`departure_country`,`departure_city`,`adults`,`children`,`reason`,`user_id`) VALUES ("Ireland","Dublin",2,2,"Other",7),("Germany","Sangerhausen",5,6,"Personal",2),("France","Tours",2,8,"Religion",10),("Brazil","Maranguape",2,7,"Religion",6),("France","Vernon",1,5,"Other",5),("Turkey","Antakya",1,2,"Religion",7),("Chile","Ercilla",1,3,"Personal",4),("Austria","Marchtrenk",3,4,"Economics",3),("New Zealand","Ashburton",3,5,"Other",5),("Austria","Bludenz",2,8,"Education",4);
INSERT INTO `human_migrations` (`departure_country`,`departure_city`,`adults`,`children`,`reason`,`user_id`) VALUES ("Chile","Rinconada",4,10,"Economics",1),("Brazil","Carapicuíba",1,4,"War",7),("United States","Springdale",3,5,"Economics",8),("Germany","Eckernförde",3,9,"Education",7),("United Kingdom","Newport",4,7,"Religion",3),("Costa Rica","Nicoya",5,4,"Religion",5),("Costa Rica","Guadalupe",5,10,"Economics",10),("Chile","Vicuña",5,9,"Other",5),("Australia","Bundaberg",1,1,"War",4),("Netherlands","Terneuzen",4,6,"Education",8);
INSERT INTO `human_migrations` (`departure_country`,`departure_city`,`adults`,`children`,`reason`,`user_id`) VALUES ("Ireland","Belfast",1,10,"Economics",1),("Nigeria","Katsina",3,3,"Religion",1),("Sweden","Värnamo",4,10,"Economics",3),("Austria","Lauterach",1,10,"War",6),("Poland","Katowice",1,5,"Economics",5),("Turkey","Mustafakemalpaşa",5,8,"Economics",6),("Ireland","Cork",5,3,"War",1),("Poland","Zielona Góra",5,8,"War",6),("France","Nantes",4,4,"Economics",7),("Sweden","Mora",1,8,"Personal",2);
INSERT INTO `human_migrations` (`departure_country`,`departure_city`,`adults`,`children`,`reason`,`user_id`) VALUES ("Costa Rica","Nicoya",4,9,"Religion",4),("Canada","Cambridge Bay",5,8,"Personal",2),("Germany","Rastatt",1,7,"War",7),("Germany","Görlitz",3,3,"Education",8),("United States","Honolulu",2,1,"Religion",1),("Poland","Gorzów Wielkopolski",1,7,"Economics",3),("Austria","Vienna",4,9,"War",7),("Australia","Tamworth",5,3,"War",4),("Poland","Tomaszów Mazowiecki",5,3,"Education",4),("Turkey","Gölcük",2,10,"Religion",3);
INSERT INTO `human_migrations` (`departure_country`,`departure_city`,`adults`,`children`,`reason`,`user_id`) VALUES ("Sweden","Ludvika",2,10,"War",9),("Italy","Ortonovo",3,10,"Economics",3),("Italy","San Donato di Ninea",1,10,"Economics",10),("Italy","Castel Maggiore",1,9,"War",3),("Brazil","Guarulhos",2,6,"Other",5),("United Kingdom","Torquay",2,10,"Economics",6),("France","Lunel",2,3,"Personal",4),("Costa Rica","Tejar",5,1,"Economics",4),("Brazil","Belford Roxo",3,2,"Personal",7),("Chile","Nogales",3,1,"Religion",6);
/
UPDATE `human_migrations` SET `arrival_country` = "France", `arrival_city` = "Moulins" WHERE `id` = 1;
UPDATE `human_migrations` SET `arrival_country` = "New Zealand", `arrival_city` = "Waiuku" WHERE `id` = 2;
UPDATE `human_migrations` SET `arrival_country` = "Chile", `arrival_city` = "Paine" WHERE `id` = 3;
UPDATE `human_migrations` SET `arrival_country` = "Italy", `arrival_city` = "Torino" WHERE `id` = 4;
UPDATE `human_migrations` SET `arrival_country` = "Brazil", `arrival_city` = "Sousa" WHERE `id` = 5;
UPDATE `human_migrations` SET `arrival_country` = "Ireland", `arrival_city` = "Dublin" WHERE `id` = 6;
UPDATE `human_migrations` SET `arrival_country` = "Nigeria", `arrival_city` = "Bama" WHERE `id` = 7;
UPDATE `human_migrations` SET `arrival_country` = "United States", `arrival_city` = "Henderson" WHERE `id` = 8;
UPDATE `human_migrations` SET `arrival_country` = "United Kingdom", `arrival_city` = "Kelso" WHERE `id` = 9;
UPDATE `human_migrations` SET `arrival_country` = "Australia", `arrival_city` = "Joondalup" WHERE `id` = 10;
UPDATE `human_migrations` SET `arrival_country` = "United States", `arrival_city` = "Columbia" WHERE `id` = 11;
UPDATE `human_migrations` SET `arrival_country` = "Costa Rica", `arrival_city` = "Cañas" WHERE `id` = 12;
UPDATE `human_migrations` SET `arrival_country` = "United Kingdom", `arrival_city` = "Matlock" WHERE `id` = 13;
UPDATE `human_migrations` SET `arrival_country` = "Spain", `arrival_city` = "Vigo" WHERE `id` = 14;
UPDATE `human_migrations` SET `arrival_country` = "Turkey", `arrival_city` = "Dörtyol" WHERE `id` = 15;
UPDATE `human_migrations` SET `arrival_country` = "Turkey", `arrival_city` = "Viranşehir" WHERE `id` = 16;
UPDATE `human_migrations` SET `arrival_country` = "Italy", `arrival_city` = "Salice Salentino" WHERE `id` = 17;
UPDATE `human_migrations` SET `arrival_country` = "Sweden", `arrival_city` = "Alingsås" WHERE `id` = 18;
UPDATE `human_migrations` SET `arrival_country` = "United Kingdom", `arrival_city` = "Runcorn" WHERE `id` = 19;
UPDATE `human_migrations` SET `arrival_country` = "Australia", `arrival_city` = "Port Lincoln" WHERE `id` = 20;
UPDATE `human_migrations` SET `arrival_country` = "France", `arrival_city` = "Pontarlier" WHERE `id` = 21;
UPDATE `human_migrations` SET `arrival_country` = "New Zealand", `arrival_city` = "Oamaru" WHERE `id` = 22;
UPDATE `human_migrations` SET `arrival_country` = "Nigeria", `arrival_city` = "Gboko" WHERE `id` = 23;
UPDATE `human_migrations` SET `arrival_country` = "New Zealand", `arrival_city` = "Temuka" WHERE `id` = 24;
UPDATE `human_migrations` SET `arrival_country` = "Nigeria", `arrival_city` = "Bauchi" WHERE `id` = 25;
UPDATE `human_migrations` SET `arrival_country` = "France", `arrival_city` = "Châlons-en-Champagne" WHERE `id` = 26;
UPDATE `human_migrations` SET `arrival_country` = "Nigeria", `arrival_city` = "Dutse" WHERE `id` = 27;
UPDATE `human_migrations` SET `arrival_country` = "Netherlands", `arrival_city` = "Spalbeek" WHERE `id` = 28;
UPDATE `human_migrations` SET `arrival_country` = "Turkey", `arrival_city` = "Körfez" WHERE `id` = 29;
UPDATE `human_migrations` SET `arrival_country` = "Belgium", `arrival_city` = "Heist-aan-Zee" WHERE `id` = 30;
UPDATE `human_migrations` SET `arrival_country` = "United States", `arrival_city` = "Hillsboro" WHERE `id` = 31;
UPDATE `human_migrations` SET `arrival_country` = "India", `arrival_city` = "Kavaratti" WHERE `id` = 32;
UPDATE `human_migrations` SET `arrival_country` = "India", `arrival_city` = "Puri" WHERE `id` = 33;
UPDATE `human_migrations` SET `arrival_country` = "Spain", `arrival_city` = "Cartagena" WHERE `id` = 34;
UPDATE `human_migrations` SET `arrival_country` = "Austria", `arrival_city` = "Steyr" WHERE `id` = 35;
UPDATE `human_migrations` SET `arrival_country` = "Turkey", `arrival_city` = "Kozan" WHERE `id` = 36;
UPDATE `human_migrations` SET `arrival_country` = "India", `arrival_city` = "Tirunelveli" WHERE `id` = 37;
UPDATE `human_migrations` SET `arrival_country` = "Turkey", `arrival_city` = "Edremit" WHERE `id` = 38;
UPDATE `human_migrations` SET `arrival_country` = "Spain", `arrival_city` = "Teruel" WHERE `id` = 39;
UPDATE `human_migrations` SET `arrival_country` = "United Kingdom", `arrival_city` = "Fort William" WHERE `id` = 40;
UPDATE `human_migrations` SET `arrival_country` = "Chile", `arrival_city` = "San Antonio" WHERE `id` = 41;
UPDATE `human_migrations` SET `arrival_country` = "India", `arrival_city` = "Delhi" WHERE `id` = 42;
UPDATE `human_migrations` SET `arrival_country` = "Italy", `arrival_city` = "San Lorenzo Nuovo" WHERE `id` = 43;
UPDATE `human_migrations` SET `arrival_country` = "New Zealand", `arrival_city` = "Waiheke Island" WHERE `id` = 44;
UPDATE `human_migrations` SET `arrival_country` = "Germany", `arrival_city` = "Regensburg" WHERE `id` = 45;
UPDATE `human_migrations` SET `arrival_country` = "Costa Rica", `arrival_city` = "Tejar" WHERE `id` = 46;
UPDATE `human_migrations` SET `arrival_country` = "Brazil", `arrival_city` = "Petrópolis" WHERE `id` = 47;
UPDATE `human_migrations` SET `arrival_country` = "Sweden", `arrival_city` = "Norrköping" WHERE `id` = 48;
UPDATE `human_migrations` SET `arrival_country` = "Germany", `arrival_city` = "Düsseldorf" WHERE `id` = 49;
UPDATE `human_migrations` SET `arrival_country` = "United Kingdom", `arrival_city` = "Bodmin" WHERE `id` = 50;
UPDATE `human_migrations` SET `arrival_country` = "India", `arrival_city` = "Cuttack" WHERE `id` = 51;
UPDATE `human_migrations` SET `arrival_country` = "Belgium", `arrival_city` = "Lasne-Chapelle-Saint-Lambert" WHERE `id` = 52;
UPDATE `human_migrations` SET `arrival_country` = "France", `arrival_city` = "Châlons-en-Champagne" WHERE `id` = 53;
UPDATE `human_migrations` SET `arrival_country` = "Italy", `arrival_city` = "Vito d'Asio" WHERE `id` = 54;
UPDATE `human_migrations` SET `arrival_country` = "Brazil", `arrival_city` = "Campina Grande" WHERE `id` = 55;
UPDATE `human_migrations` SET `arrival_country` = "New Zealand", `arrival_city` = "North Shore" WHERE `id` = 56;
UPDATE `human_migrations` SET `arrival_country` = "India", `arrival_city` = "Berhampore" WHERE `id` = 57;
UPDATE `human_migrations` SET `arrival_country` = "United Kingdom", `arrival_city` = "Musselburgh" WHERE `id` = 58;
UPDATE `human_migrations` SET `arrival_country` = "Spain", `arrival_city` = "Santander" WHERE `id` = 59;
UPDATE `human_migrations` SET `arrival_country` = "Turkey", `arrival_city` = "Akhisar" WHERE `id` = 60;
UPDATE `human_migrations` SET `arrival_country` = "Poland", `arrival_city` = "Bydgoszcz" WHERE `id` = 61;
UPDATE `human_migrations` SET `arrival_country` = "New Zealand", `arrival_city` = "Rangiora" WHERE `id` = 62;
UPDATE `human_migrations` SET `arrival_country` = "United Kingdom", `arrival_city` = "Carterton" WHERE `id` = 63;
UPDATE `human_migrations` SET `arrival_country` = "Sweden", `arrival_city` = "Finspång" WHERE `id` = 64;
UPDATE `human_migrations` SET `arrival_country` = "Italy", `arrival_city` = "Bazzano" WHERE `id` = 65;
UPDATE `human_migrations` SET `arrival_country` = "Nigeria", `arrival_city` = "Makurdi" WHERE `id` = 66;
UPDATE `human_migrations` SET `arrival_country` = "Austria", `arrival_city` = "Ternitz" WHERE `id` = 67;
UPDATE `human_migrations` SET `arrival_country` = "Poland", `arrival_city` = "Warszawa" WHERE `id` = 68;
UPDATE `human_migrations` SET `arrival_country` = "Chile", `arrival_city` = "Alto del Carmen" WHERE `id` = 69;
UPDATE `human_migrations` SET `arrival_country` = "United States", `arrival_city` = "Athens" WHERE `id` = 70;
UPDATE `human_migrations` SET `arrival_country` = "Netherlands", `arrival_city` = "Assen" WHERE `id` = 71;
UPDATE `human_migrations` SET `arrival_country` = "Netherlands", `arrival_city` = "Zwolle" WHERE `id` = 72;
UPDATE `human_migrations` SET `arrival_country` = "Nigeria", `arrival_city` = "Gboko" WHERE `id` = 73;
UPDATE `human_migrations` SET `arrival_country` = "France", `arrival_city` = "Cagnes-sur-Mer" WHERE `id` = 74;
UPDATE `human_migrations` SET `arrival_country` = "Brazil", `arrival_city` = "Sobral" WHERE `id` = 75;
UPDATE `human_migrations` SET `arrival_country` = "United Kingdom", `arrival_city` = "Eyemouth" WHERE `id` = 76;
UPDATE `human_migrations` SET `arrival_country` = "Australia", `arrival_city` = "Devonport" WHERE `id` = 77;
UPDATE `human_migrations` SET `arrival_country` = "Nigeria", `arrival_city` = "Ife" WHERE `id` = 78;
UPDATE `human_migrations` SET `arrival_country` = "Poland", `arrival_city` = "Opole" WHERE `id` = 79;
UPDATE `human_migrations` SET `arrival_country` = "Nigeria", `arrival_city` = "Ikot Ekpene" WHERE `id` = 80;
UPDATE `human_migrations` SET `arrival_country` = "Belgium", `arrival_city` = "Labuissire" WHERE `id` = 81;
UPDATE `human_migrations` SET `arrival_country` = "Austria", `arrival_city` = "Perchtoldsdorf" WHERE `id` = 82;
UPDATE `human_migrations` SET `arrival_country` = "Belgium", `arrival_city` = "Gontrode" WHERE `id` = 83;
UPDATE `human_migrations` SET `arrival_country` = "Nigeria", `arrival_city` = "Buguma" WHERE `id` = 84;
UPDATE `human_migrations` SET `arrival_country` = "France", `arrival_city` = "Angoulême" WHERE `id` = 85;
UPDATE `human_migrations` SET `arrival_country` = "Netherlands", `arrival_city` = "Medemblik" WHERE `id` = 86;
UPDATE `human_migrations` SET `arrival_country` = "Brazil", `arrival_city` = "Paranaguá" WHERE `id` = 87;
UPDATE `human_migrations` SET `arrival_country` = "France", `arrival_city` = "Aubervilliers" WHERE `id` = 88;
UPDATE `human_migrations` SET `arrival_country` = "Netherlands", `arrival_city` = "Heerenveen" WHERE `id` = 89;
UPDATE `human_migrations` SET `arrival_country` = "New Zealand", `arrival_city` = "Waiheke Island" WHERE `id` = 90;
UPDATE `human_migrations` SET `arrival_country` = "Spain", `arrival_city` = "Telde" WHERE `id` = 91;
UPDATE `human_migrations` SET `arrival_country` = "France", `arrival_city` = "Strasbourg" WHERE `id` = 92;
UPDATE `human_migrations` SET `arrival_country` = "Belgium", `arrival_city` = "Montigny-le-Tilleul" WHERE `id` = 93;
UPDATE `human_migrations` SET `arrival_country` = "Brazil", `arrival_city` = "Juazeiro do Norte" WHERE `id` = 94;
UPDATE `human_migrations` SET `arrival_country` = "Sweden", `arrival_city` = "Nässjö" WHERE `id` = 95;
UPDATE `human_migrations` SET `arrival_country` = "Chile", `arrival_city` = "Arica" WHERE `id` = 96;
UPDATE `human_migrations` SET `arrival_country` = "Turkey", `arrival_city` = "Adana" WHERE `id` = 97;
UPDATE `human_migrations` SET `arrival_country` = "Netherlands", `arrival_city` = "Sneek" WHERE `id` = 98;
UPDATE `human_migrations` SET `arrival_country` = "Brazil", `arrival_city` = "Jundiaí" WHERE `id` = 99;
UPDATE `human_migrations` SET `arrival_country` = "France", `arrival_city` = "Paris" WHERE `id` = 100;
UPDATE `human_migrations` SET `arrival_country` = "France", `arrival_city` = "Cherbourg-Octeville" WHERE `id` = 101;
UPDATE `human_migrations` SET `arrival_country` = "United Kingdom", `arrival_city` = "Wisbech" WHERE `id` = 102;
UPDATE `human_migrations` SET `arrival_country` = "Poland", `arrival_city` = "Lublin" WHERE `id` = 103;
UPDATE `human_migrations` SET `arrival_country` = "Nigeria", `arrival_city` = "Bida" WHERE `id` = 104;
UPDATE `human_migrations` SET `arrival_country` = "Chile", `arrival_city` = "Chañaral" WHERE `id` = 105;
UPDATE `human_migrations` SET `arrival_country` = "Australia", `arrival_city` = "Subiaco" WHERE `id` = 106;
UPDATE `human_migrations` SET `arrival_country` = "Canada", `arrival_city` = "Gjoa Haven" WHERE `id` = 107;
UPDATE `human_migrations` SET `arrival_country` = "Brazil", `arrival_city` = "Betim" WHERE `id` = 108;
UPDATE `human_migrations` SET `arrival_country` = "United States", `arrival_city` = "Nampa" WHERE `id` = 109;
UPDATE `human_migrations` SET `arrival_country` = "Costa Rica", `arrival_city` = "Quesada" WHERE `id` = 110;
UPDATE `human_migrations` SET `arrival_country` = "Sweden", `arrival_city` = "Norrköping" WHERE `id` = 111;
UPDATE `human_migrations` SET `arrival_country` = "Italy", `arrival_city` = "Accadia" WHERE `id` = 112;
UPDATE `human_migrations` SET `arrival_country` = "India", `arrival_city` = "Srinagar" WHERE `id` = 113;
UPDATE `human_migrations` SET `arrival_country` = "France", `arrival_city` = "Brive-la-Gaillarde" WHERE `id` = 114;
UPDATE `human_migrations` SET `arrival_country` = "Costa Rica", `arrival_city` = "Cinco Esquinas" WHERE `id` = 115;
UPDATE `human_migrations` SET `arrival_country` = "Austria", `arrival_city` = "Pinkafeld" WHERE `id` = 116;
UPDATE `human_migrations` SET `arrival_country` = "Netherlands", `arrival_city` = "Ravenstein" WHERE `id` = 117;
UPDATE `human_migrations` SET `arrival_country` = "Chile", `arrival_city` = "Huechuraba" WHERE `id` = 118;
UPDATE `human_migrations` SET `arrival_country` = "Germany", `arrival_city` = "Solingen" WHERE `id` = 119;
UPDATE `human_migrations` SET `arrival_country` = "Turkey", `arrival_city` = "Edremit" WHERE `id` = 120;
UPDATE `human_migrations` SET `arrival_country` = "United Kingdom", `arrival_city` = "Hexham" WHERE `id` = 121;
UPDATE `human_migrations` SET `arrival_country` = "India", `arrival_city` = "Panipat" WHERE `id` = 122;
UPDATE `human_migrations` SET `arrival_country` = "Italy", `arrival_city` = "Isernia" WHERE `id` = 123;
UPDATE `human_migrations` SET `arrival_country` = "Belgium", `arrival_city` = "Hanret" WHERE `id` = 124;
UPDATE `human_migrations` SET `arrival_country` = "Sweden", `arrival_city` = "Hudiksvall" WHERE `id` = 125;
UPDATE `human_migrations` SET `arrival_country` = "Chile", `arrival_city` = "Antofagasta" WHERE `id` = 126;
UPDATE `human_migrations` SET `arrival_country` = "Australia", `arrival_city` = "Broken Hill" WHERE `id` = 127;
UPDATE `human_migrations` SET `arrival_country` = "Germany", `arrival_city` = "Berlin" WHERE `id` = 128;
UPDATE `human_migrations` SET `arrival_country` = "Nigeria", `arrival_city` = "Ogbomosho" WHERE `id` = 129;
UPDATE `human_migrations` SET `arrival_country` = "Italy", `arrival_city` = "Luzzara" WHERE `id` = 130;
UPDATE `human_migrations` SET `arrival_country` = "United States", `arrival_city` = "Kapolei" WHERE `id` = 311;
UPDATE `human_migrations` SET `arrival_country` = "Canada", `arrival_city` = "Sunset Point" WHERE `id` = 132;
UPDATE `human_migrations` SET `arrival_country` = "Chile", `arrival_city` = "Monte Patria" WHERE `id` = 133;
UPDATE `human_migrations` SET `arrival_country` = "Italy", `arrival_city` = "Siculiana" WHERE `id` = 134;
UPDATE `human_migrations` SET `arrival_country` = "India", `arrival_city` = "Warangal" WHERE `id` = 135;
UPDATE `human_migrations` SET `arrival_country` = "Nigeria", `arrival_city` = "Gboko" WHERE `id` = 136;
UPDATE `human_migrations` SET `arrival_country` = "India", `arrival_city` = "Kohima" WHERE `id` = 137;
UPDATE `human_migrations` SET `arrival_country` = "Netherlands", `arrival_city` = "Hindeloopen" WHERE `id` = 138;
UPDATE `human_migrations` SET `arrival_country` = "Turkey", `arrival_city` = "Söke" WHERE `id` = 139;
UPDATE `human_migrations` SET `arrival_country` = "Nigeria", `arrival_city` = "Owerri" WHERE `id` = 140;
UPDATE `human_migrations` SET `arrival_country` = "Ireland", `arrival_city` = "Belfast" WHERE `id` = 141;
UPDATE `human_migrations` SET `arrival_country` = "Turkey", `arrival_city` = "Darıca" WHERE `id` = 142;
UPDATE `human_migrations` SET `arrival_country` = "Brazil", `arrival_city` = "Ilhéus" WHERE `id` = 143;
UPDATE `human_migrations` SET `arrival_country` = "Poland", `arrival_city` = "Warszawa" WHERE `id` = 144;
UPDATE `human_migrations` SET `arrival_country` = "Nigeria", `arrival_city` = "Sokoto" WHERE `id` = 145;
UPDATE `human_migrations` SET `arrival_country` = "Italy", `arrival_city` = "Pagazzano" WHERE `id` = 146;
UPDATE `human_migrations` SET `arrival_country` = "Germany", `arrival_city` = "Berlin" WHERE `id` = 147;
UPDATE `human_migrations` SET `arrival_country` = "Ireland", `arrival_city` = "Cork" WHERE `id` = 148;
UPDATE `human_migrations` SET `arrival_country` = "Austria", `arrival_city` = "Höchst" WHERE `id` = 149;
UPDATE `human_migrations` SET `arrival_country` = "Nigeria", `arrival_city` = "Onitsha" WHERE `id` = 150;
UPDATE `human_migrations` SET `arrival_country` = "Brazil", `arrival_city` = "Uberlândia" WHERE `id` = 151;
UPDATE `human_migrations` SET `arrival_country` = "Belgium", `arrival_city` = "Marneffe" WHERE `id` = 152;
UPDATE `human_migrations` SET `arrival_country` = "Turkey", `arrival_city` = "Bursa" WHERE `id` = 153;
UPDATE `human_migrations` SET `arrival_country` = "Costa Rica", `arrival_city` = "Guápiles" WHERE `id` = 154;
UPDATE `human_migrations` SET `arrival_country` = "Nigeria", `arrival_city` = "Bauchi" WHERE `id` = 155;
UPDATE `human_migrations` SET `arrival_country` = "Poland", `arrival_city` = "Konin" WHERE `id` = 156;
UPDATE `human_migrations` SET `arrival_country` = "Nigeria", `arrival_city` = "Dutse" WHERE `id` = 157;
UPDATE `human_migrations` SET `arrival_country` = "Canada", `arrival_city` = "Red Deer" WHERE `id` = 158;
UPDATE `human_migrations` SET `arrival_country` = "Belgium", `arrival_city` = "Mont-sur-Marchienne" WHERE `id` = 159;
UPDATE `human_migrations` SET `arrival_country` = "Sweden", `arrival_city` = "Värnamo" WHERE `id` = 160;
UPDATE `human_migrations` SET `arrival_country` = "Australia", `arrival_city` = "Dandenong" WHERE `id` = 161;
UPDATE `human_migrations` SET `arrival_country` = "New Zealand", `arrival_city` = "Christchurch" WHERE `id` = 162;
UPDATE `human_migrations` SET `arrival_country` = "Italy", `arrival_city` = "Varena" WHERE `id` = 163;
UPDATE `human_migrations` SET `arrival_country` = "Belgium", `arrival_city` = "HavrŽ" WHERE `id` = 164;
UPDATE `human_migrations` SET `arrival_country` = "Italy", `arrival_city` = "Gressoney-Saint-Jean" WHERE `id` = 165;
UPDATE `human_migrations` SET `arrival_country` = "India", `arrival_city` = "Jammu" WHERE `id` = 166;
UPDATE `human_migrations` SET `arrival_country` = "Germany", `arrival_city` = "Pirna" WHERE `id` = 167;
UPDATE `human_migrations` SET `arrival_country` = "Belgium", `arrival_city` = "Souvret" WHERE `id` = 168;
UPDATE `human_migrations` SET `arrival_country` = "France", `arrival_city` = "Orléans" WHERE `id` = 169;
UPDATE `human_migrations` SET `arrival_country` = "Canada", `arrival_city` = "Whitehorse" WHERE `id` = 170;
UPDATE `human_migrations` SET `arrival_country` = "Sweden", `arrival_city` = "Borlänge" WHERE `id` = 171;
UPDATE `human_migrations` SET `arrival_country` = "Sweden", `arrival_city` = "Värnamo" WHERE `id` = 172;
UPDATE `human_migrations` SET `arrival_country` = "Brazil", `arrival_city` = "São José" WHERE `id` = 173;
UPDATE `human_migrations` SET `arrival_country` = "Canada", `arrival_city` = "Stratford" WHERE `id` = 714;
UPDATE `human_migrations` SET `arrival_country` = "Spain", `arrival_city` = "Logroño" WHERE `id` = 175;
UPDATE `human_migrations` SET `arrival_country` = "Australia", `arrival_city` = "Wodonga" WHERE `id` = 176;
UPDATE `human_migrations` SET `arrival_country` = "France", `arrival_city` = "Martigues" WHERE `id` = 177;
UPDATE `human_migrations` SET `arrival_country` = "Poland", `arrival_city` = "Gorzów Wielkopolski" WHERE `id` = 178;
UPDATE `human_migrations` SET `arrival_country` = "India", `arrival_city` = "Kavaratti" WHERE `id` = 179;
UPDATE `human_migrations` SET `arrival_country` = "Belgium", `arrival_city` = "Perwez" WHERE `id` = 180;
UPDATE `human_migrations` SET `arrival_country` = "Poland", `arrival_city` = "Tarnów" WHERE `id` = 181;
UPDATE `human_migrations` SET `arrival_country` = "Nigeria", `arrival_city` = "Sokoto" WHERE `id` = 182;
UPDATE `human_migrations` SET `arrival_country` = "New Zealand", `arrival_city` = "Oamaru" WHERE `id` = 183;
UPDATE `human_migrations` SET `arrival_country` = "Belgium", `arrival_city` = "Roselies" WHERE `id` = 184;
UPDATE `human_migrations` SET `arrival_country` = "Costa Rica", `arrival_city` = "San Francisco" WHERE `id` = 185;
UPDATE `human_migrations` SET `arrival_country` = "Nigeria", `arrival_city` = "Port Harcourt" WHERE `id` = 186;
UPDATE `human_migrations` SET `arrival_country` = "Canada", `arrival_city` = "Fort Providence" WHERE `id` = 187;
UPDATE `human_migrations` SET `arrival_country` = "Italy", `arrival_city` = "Reana del Rojale" WHERE `id` = 188;
UPDATE `human_migrations` SET `arrival_country` = "Ireland", `arrival_city` = "Galway" WHERE `id` = 189;
UPDATE `human_migrations` SET `arrival_country` = "Austria", `arrival_city` = "Mattersburg" WHERE `id` = 190;
UPDATE `human_migrations` SET `arrival_country` = "Turkey", `arrival_city` = "Burhaniye" WHERE `id` = 191;
UPDATE `human_migrations` SET `arrival_country` = "Costa Rica", `arrival_city` = "Cañas" WHERE `id` = 192;
UPDATE `human_migrations` SET `arrival_country` = "Costa Rica", `arrival_city` = "Cañas" WHERE `id` = 193;
UPDATE `human_migrations` SET `arrival_country` = "Costa Rica", `arrival_city` = "Siquirres" WHERE `id` = 194;
UPDATE `human_migrations` SET `arrival_country` = "Canada", `arrival_city` = "Flin Flon" WHERE `id` = 195;
UPDATE `human_migrations` SET `arrival_country` = "Costa Rica", `arrival_city` = "Barranca" WHERE `id` = 196;
UPDATE `human_migrations` SET `arrival_country` = "Nigeria", `arrival_city` = "Dutse" WHERE `id` = 197;
UPDATE `human_migrations` SET `arrival_country` = "Canada", `arrival_city` = "Marystown" WHERE `id` = 198;
UPDATE `human_migrations` SET `arrival_country` = "Italy", `arrival_city` = "Novoli" WHERE `id` = 199;
UPDATE `human_migrations` SET `arrival_country` = "India", `arrival_city` = "Eluru" WHERE `id` = 200;
